version: "3.3"
services:
  traefik:
    image: "traefik:v2.10"
    container_name: traefik
    restart: "always"
    command:
      - "--configFile=traefik.yml"
    ports:
      - "80:80"
      # - "443:443"
      # Port 8080 is used for traefik's own dashboard
      - "8080:8080"
      # apis use this
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  api1:
    container_name: api1
    image: api1
    labels:
      - app:api1
      - traefik.enable=true
      - traefik.http.routers.api1.entrypoints=api1
      - traefik.http.routers.api1.rule=Host("api.${SUBDOMAIN}${DOMAIN}") && PathPrefix(`/`)
      - traefik.http.services.api1.loadbalancer.server.port=5000
    environment:
      API2_URL        : http://api2:3000
      PORT            : 5000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: sh -c "python -m uvicorn main:app --reload --host 0.0.0.0 --port 5000"
    build: 
      context: ../api1/.
      args:
      - ENVIRONMENT=localhost
      # target: build
    volumes:
      - ../api1/.:/app
    links:
      - api2
  api2:
    container_name: api2
    image: api2
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entrypoints=api
      - traefik.http.routers.api.rule=Host("api.${SUBDOMAIN}${DOMAIN}") && PathPrefix(`/`)
      - traefik.http.services.api.loadbalancer.server.port=3000
    environment:
      ATLAS_URI       : mongodb://rootusername:changethispassword@mongodb
      DB_NAME         : mainDB
      PORT            : 3000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: sh -c "python -m uvicorn main:app --reload --host 0.0.0.0 --port 3000"
    build: 
      context: ../api2/.
      args:
      - ENVIRONMENT=localhost
      # target: build
    volumes:
      - ../api2/.:/app
    links:
      - mongodb
  mongodb:
    image: mongo:4.4
    labels:
      - "not open to external"
      # - "traefik.enable=false"
      # - "traefik.http.services.nodejsapp.loadbalancer.server.port=27017"
      # - "traefik.http.routers.nodejsapp.rule=Host(`mongodb.tg.localhost`)"
    container_name: mongodb
    environment:
      - MONGODB_DATABASE='mainDB'
      - MONGO_INITDB_ROOT_USERNAME=rootusername
      - MONGO_INITDB_ROOT_PASSWORD=changethispassword
    # Uncoment this if you want to see database beeing created in local folder
    # volumes:
    #    - ./database:/data/db
    ports:
      - 27017:27017
  integrationtestL1:
    image: integrationtestl1
    profiles: ["integrationtestL1"]
    build:
      context: ../testing/integrationL1/.
    environment:
      - API1_URL=api2:3000
    links:
      - mongodb
      - api2
  integrationtestL2:
    image: integrationtestl2
    profiles: ["integrationtestL2"]
    build:
      context: ../testing/integrationL2/.
    environment:
      - API1_URL=api1:5000
      - API2_URL=api2:3000
    links:
      - mongodb
      - api1
      - api2