api:
  insecure: true
  dashboard: true

api1:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedbydefault: false
    watch: true
    network: "bridge"

http: 
  routers:
    api:
      entrypoints: 
      - "web"
      service: "api@internal"
      rule: "Host(`localhost`)"

entrypoints: 
  web:
    address:  :80
  api:
    address:  :3000
  api1:
    address:  :5000

log:
  level: DEBUG

